spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring-todo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 2c4c8d67fc514d027e773dcb511ce09ab09c1aef7a1a419eecae7843040f0245
  expiration: 1800000

logging:
  level:
    org.hibernate.sql: debug
